Revert "miatoll: Re-enable broken dup rules check"
* I still need it for prebuilt camera

Fixes:
error: overriding commands for target `out/target/product/miatoll/vendor/etc/init/android.hardware.camera.provider@2.4-service_64.rc', previously defined at out/soong/installs-pixelage_miatoll.mk

This reverts commit 928e88107772247f525e9656e754733b072d32d6.